[+]actions

diff --git a/.github/workflows/compile.yml b/.github/workflows/compile.yml
--- a/.github/workflows/compile.yml
+++ b/.github/workflows/compile.yml
@@ -10,15 +10,15 @@ jobs:
       runs-on: ubuntu-latest
 
     steps:
-        - name: checkout-code
-          uses: actions/checkout@v2
+      - name: checkout-code
+        uses: actions/checkout@v2
 
-        - name: compile-program
-          run: |
-            make
-            if [$? -eq 0]; then
-              echo "Compilation Success"
-              exit 0
-            else
-              echo "Compilation Failed"
-              exit 1
+      - name: compile-program
+        run: |
+          make
+          if [$? -eq 0]; then
+            echo "Compilation Success"
+            exit 0
+          else
+            echo "Compilation Failed"
+            exit 1
